SELECT * FROM ROLE;
SELECT * FROM SYSTEMUSER; 
-- bam, 3

INSERT INTO ROLE (NAME, MASK) VALUES('EMPLOYER', 0);
INSERT INTO ROLE (NAME, MASK) VALUES('JOBSEEKER', 0);

SELECT * FROM USER_ROLE;

INSERT INTO USER_ROLE (USERNAME, ROLENAME, USER, ROLE, AUTHORITY) VALUES ('bam', 'JOBSEEKER', 3, 1, '');

INSERT INTO USER_ROLE (USERNAME, ROLENAME, USER, ROLE, AUTHORITY) 
VALUES ('employer', 'EMPLOYER', 4, 1, '');

SELECT ROLENAME FROM USER_ROLE WHERE USERNAME = 'employer';
