-- these are needed to create jobseeker and employers.
INSERT INTO ROLE (NAME, MASK, CODE, CRTBY) VALUES('JOBSEEKER', 0, 1, 'MASTERDML');
INSERT INTO ROLE (NAME, MASK, CODE, CRTBY) VALUES('EMPLOYER', 0, 2, 'MASTERDML');

